plugins {
	id 'net.fabricmc.fabric-loom-remap'
	id 'com.modrinth.minotaur'
	id 'net.darkhax.curseforgegradle'
}

loom {
	splitEnvironmentSourceSets()
	accessWidenerPath = project(":common").file("src/main/resources/create.accesswidener")

	mods {
		"create" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
			sourceSet project(":common").sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"

	implementation project(":common")
}

processResources {
	def version = project.version
	def minecraftDependency = project.minecraft_dependency
	def fabricLoaderDependency = project.fabric_loader_dependency
	def javaVersion = project.java_version
	inputs.property "version", version
	inputs.property "minecraftDependency", minecraftDependency
	inputs.property "fabricLoaderDependency", fabricLoaderDependency
	inputs.property "javaVersion", javaVersion

	filesMatching("fabric.mod.json") {
		expand "version": version,
				"minecraftDependency": minecraftDependency,
				"fabricLoaderDependency": fabricLoaderDependency,
				"javaVersion": javaVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
}

java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.java_version))
	}
}

jar {
	archiveFileName = "create-${project.mod_version}-${project.mc_version_suffix}-fabric.jar"
	def projectName = project.name
	inputs.property "projectName", projectName

	from project(":common").sourceSets.main.output

	if (rootProject.file("LICENSE.md").exists()) {
		from(rootProject.file("LICENSE.md")) {
			rename { "${it}_$projectName"}
		}
	}
}

remapJar {
	archiveFileName = "create-${project.mod_version}-${project.mc_version_suffix}-fabric.jar"
}

tasks.register('copyJarToRelease', Copy) {
	from tasks.named('remapJar')
	into "${project.rootDir}/release"
}

tasks.named('build') {
	finalizedBy('copyJarToRelease')
}

loom {
	mixin {
		useLegacyMixinAp = false
	}
}
